<?php

namespace Orchestra\Testbench\Factories;

use WpStarter\Database\Eloquent\Factories\Factory;
use WpStarter\Foundation\Auth\User;
use WpStarter\Support\Facades\Hash;
use WpStarter\Support\Str;

/**
 * @phpstan-type TModel \WpStarter\Foundation\Auth\User
 *
 * @extends \WpStarter\Database\Eloquent\Factories\Factory<TModel>
 *
 * @property class-string<\WpStarter\Database\Eloquent\Model|TModel>|null $model
 */
class UserFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => ws_fake()->name(),
            'email' => ws_fake()->unique()->safeEmail(),
            'email_verified_at' => ws_now(),
            'password' => static::$password ??= Hash::make('password'),
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string<\WpStarter\Database\Eloquent\Model|TModel>
     */
    public function modelName()
    {
        return $this->model ?? ws_config('auth.providers.users.model') ?? ws_env('AUTH_MODEL', User::class);
    }
}
